### PR TITLE
9 multiple lists

### LINKED ISSUE #9: Multiple Lists
Users might want to have multiple lists. For example, they could have a to do list and a shopping list. In this issue, we need to implement both the data structures to handle multiple lists, and the UI to display multiple lists.

* Update the list persistence logic to support multiple lists.
    * Each list should have a title, along with a unique ID to identify it.
    * The unique id can be generated with a library like [uuid](https://pub.dev/packages/uuid).
    * Don't display the ID to the user, just the title and items
* Add a new page to the app, that displays the list of lists
    * This should be the home page of the app, the page that the app opens to when it starts.
        * You could even name it `HomePage`.
    * Including a FAB that allows the user to add new lists.
    * Users should be prompted with a dialog to enter the title of their new list.
    * When a user taps on a list, use `Navigator.push` to take them to the `ListWidget` for that list.
* Update `ListWidget` to display the current list's title in the AppBar.

### PR DESCRIPTION
**Pull request by tycebrown**
Some design questions/considerations/comments:

- Now, `DatabaseManager` stores a cache of the `ListModel`s and provides a getter for a view of the cache. Should I have a cache? Should it be the `DatabaseManager`'s responsibility?
- In the `DatabaseManager`'s cache, I used `assert` statements for error "handling" (which would compile to nothing in release).  Should I switch to another method? 
- I noticed that `HomePage` and `ListWidget` have a lot of overlap (as do `ListPreviewWidget` (which, by the way, is up for renaming) and `ItemWidget`). How do you imagine these should be refactored (if at all)? 
- Finally, one last note: I used a `Set` to store the cache. However, if we wanted to move items around in the list, things would be slightly more involved. Should I switch to another data structure for the cache? 

God bless you!

### CODE REVIEW

**Comment by Pertempto** [comment]
What is the purpose of the cache? It seems to just add extra complexity. Was the app slow without it?

**Comment by Pertempto** [comment]
> * I noticed that `HomePage` and `ListWidget` have a lot of overlap (as do `ListPreviewWidget` (which, by the way, is up for renaming) and `ItemWidget`). How do you imagine these should be refactored (if at all)?


The overlap will get less and less as we add some of the more powerful features. I don't think it is a concern at this point.

**Comment by tycebrown** [comment]
> What is the purpose of the cache? It seems to just add extra complexity. Was the app slow without it?

Originally, my design was that all the `ListModel`'s would be loaded once at the beginning of the program and stashed somewhere. Then, these cached `ListModel`'s would be used throughout the app. I abstracted this functionality into the `_Cache` class in the `DatabaseManager`, so that managing this "stash" (as `ListModel`'s were added and deleted in the app) would be the `DatabaseManager`'s responsibility rather than the `HomePage`'s.

However, after testing, it seems that this does not have any speed advantage over simply loading all the `ListModel`'s each time they need to be displayed in the `HomePage`.

This was a mistake on my part. Will fix and try to avoid premature optimizations in the future.

**Comment by Pertempto** [comment]
Ok! Yes, it's always good to avoid premature optimization. Do some research on that term and you'll see some reasons why. Focus on writing code that is easy to read and work with. When you end up with something that performs slowly, that's when you start trying to figure out how to optimize for performance.

**Comment by tycebrown** [comment]
> Ok! Yes, it's always good to avoid premature optimization. Do some research on that term and you'll see some reasons why. Focus on writing code that is easy to read and work with. When you end up with something that performs slowly, that's when you start trying to figure out how to optimize for performance.

Will do, thanks!

**Review by Pertempto — APPROVED** [review]
Looking good! 👍🏽

**Pull request merged**
