### PR TITLE
App Icon

### LINKED ISSUE #35: Add a Proper App Icon
The app should use an actual icon, instead of the generic Flutter app icon.

@tycebrown what should it look like?

### PR DESCRIPTION
**Pull request by tycebrown**
Closes #35

### CODE REVIEW

**Comment by Pertempto** [comment]
Personally, I'm not a big fan of the black background for the notepad.

**Comment by Pertempto** [comment]
I'm not sure what would be better though, and this looks nice

**Review by Pertempto — APPROVED** [review]
It looks good! If we come up with a different idea later, we can change it then.

Did you generate these from an SVG file? If so, please upload it in a comment for future reference.

**Comment by tycebrown** [comment]
> Did you generate these from an SVG file? 

Yes, partially, but I threw it away after exporting the icon as a png file. I should have saved it.

Only partially, because I edited it further in [Gimp](https://www.gimp.org/)

**Comment by Pertempto** [comment]
> 
> Yes, partially, but I threw it away after exporting the icon as a png file. I should have saved it.


Oops! That's the danger of removing files pre-maturely.


> Only partially, because I edited it further in [Gimp](https://www.gimp.org/)

Ok, can you upload the base PNG then? We want something that we can easily edit in the future if we want to make modifications.

**Comment by tycebrown** [comment]
> Ok, can you upload the base PNG then? We want something that we can easily edit in the future if we want to make modifications.

Before I did the additional Gimp editing? I think I threw away the original, but I kept a "higher-quality" (same dimensions minus the padding, more bytes used) image generated from the original. Here it is:
Before editing

I did some work and recreated the icon as an svg. It is a little different; most notably, the pencil is longer. However, everything is in about the same place. Here it is:
lists_app_icon

Before recreating as an svg:
old_app_icon

I've stashed away the old app icon and the new, recreated one.

Was this the appropriate action? 

I also committed this new icon. Should I make a PR/MR?

**Comment by Pertempto** [comment]
Sure, you can make a PR

**Pull request merged**
